# ====================
# ansible/roles/common/tasks/main.yml
# ====================
---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: '0644'

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab
  when: disable_swap | bool

- name: Disable SELinux
  selinux:
    state: "{{ selinux_mode }}"
  when: selinux_mode is defined

- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Ensure kernel modules load on boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Set sysctl parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  loop:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }

- name: Install required packages
  dnf:
    name:
      - curl
      - wget
      - vim
      - git
      - tar
      - socat
      - conntrack
      - ipset
      - iproute-tc
    state: present

- name: Configure firewall for Kubernetes
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 6443/tcp    # Kubernetes API server
    - 2379-2380/tcp  # etcd server client API
    - 10250/tcp   # Kubelet API
    - 10251/tcp   # kube-scheduler
    - 10252/tcp   # kube-controller-manager
    - 10255/tcp   # Read-only Kubelet API
  when: configure_firewall | bool and inventory_hostname in groups['masters']

- name: Configure firewall for workers
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 10250/tcp   # Kubelet API
    - 30000-32767/tcp  # NodePort Services
  when: configure_firewall | bool and inventory_hostname in groups['workers']
