# ====================
# ansible/roles/kubernetes-master-join/tasks/main.yml
# ====================
---
- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join additional master nodes
  shell: "{{ hostvars['JOIN_COMMANDS']['master_join'] }} --control-plane --apiserver-advertise-address={{ apiserver_advertise_address }}"
  when: not kubelet_conf.stat.exists and hostvars['JOIN_COMMANDS']['master_join'] != ''

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf from first master
  shell: |
    scp -o StrictHostKeyChecking=no {{ hostvars[groups['masters'][0]]['ansible_host'] }}:/etc/kubernetes/admin.conf /root/.kube/config
  when: not kubelet_conf.stat.exists

- name: Set kubeconfig permissions
  file:
    path: /root/.kube/config
    mode: '0600'
