# ====================
# ansible/roles/kubernetes-networking/tasks/main.yml
# ====================
---
- name: Install Calico CNI
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.4/manifests/calico.yaml
  when: kubernetes_cni == "calico"

- name: Install Flannel CNI
  shell: |
    kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  when: kubernetes_cni == "flannel"

- name: Wait for all nodes to be ready
  shell: kubectl get nodes | grep -c " Ready"
  register: ready_nodes
  until: ready_nodes.stdout | int == groups['k8s_cluster'] | length
  retries: 30
  delay: 10

- name: Get cluster status
  shell: kubectl get nodes -o wide
  register: cluster_status

- name: Display cluster status
  debug:
    msg: "{{ cluster_status.stdout_lines }}"
